language: node_js
node_js:
  - "7"
  - "10"
install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
- npm install
- ./node_modules/.bin/lerna bootstrap
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script: npm run-script test-on-travis
